### ISSUE TITLE
Remove Yaru*Row widgets 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#200]
They are basically only material rows with something inside. We should move them back to settings

**Comment by jpnurmi** [comment]
How about moving them to `packages/yaru_settings` or such in the settings repo to have them separate from the app? We could still easily enough reuse them to implement in-app settings in other projects:

```yaml
yaru_settings:
  git:
    url: https://github.com/ubuntu-flutter-community/settings.git
    path: packages/yaru_settings
```
